- name: Setup Docker
  hosts: homelab
  become: true
  tags: packages
  roles:
    - role: geerlingguy.docker
      vars:
        docker_users:
          - "{{ ansible_user }}"

  post_tasks:
    - name: Create homelab Docker network
      community.docker.docker_network:
        name: homelab
        state: present
